before_install:
  - npm install -g yarn

language: node_js

cache: yarn
install: yarn

env: POSTGRES=postgres://postgres@localhost:5432/travis_ci_test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
